### ISSUE TITLE
Query: Is the bridging done between Ruma (homeserver) and Rocket.Chat?

### ISSUE THREAD

**Issue by madguy02** [exul/matrix-rocketchat#58]
Description: I wanted to know if the bridge is created targeting Ruma as the HomeServer? Or will it be similar to a full-fledged AS designed to bridge RC with any home servers?

**Comment by exul** [comment]
The bridge doesn't target any specific homeserver. It will work with any homeserver that provides the application service and the client server endpoints according to the Matrix spec.

**Comment by madguy02** [comment]
Ok cool :) thanks for the info
